"""add image_file to post

Revision ID: 20223973cf28
Revises: 
Create Date: 2025-08-29 17:08:28.721164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20223973cf28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
